FullstackMVC/Controllers/CharacterController.cs
using FullstackMVC.Data;
using FullstackMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FullstackMVC.Controllers
{
    public class CharacterController : Controller
    {

        private readonly ApplicationDbContext _db;

        public CharacterController( ApplicationDbContext db)
        {        
            _db = db;
        }


        public IActionResult Index()
        {
            ApplicationUserModel applicationUserModel = new ApplicationUserModel();

            // IEnumerable<MonsterModel> MonsterList = _db.MonsterModel.Include(x => x.MonsterTypeModel).Include(x => x.MapModel);
            var accountHasCharacterValidation = _db.ApplicationUserModel.FirstOrDefault(x => x.UserName == User.Identity.Name);
            accountHasCharacterValidation.Character = _db.CharacterModel.FirstOrDefault(x => x.Id == accountHasCharacterValidation.CharacterId);

            if (accountHasCharacterValidation.CharacterId == null)
            {
                return View("Create");
            }
            else
            {
                return View(accountHasCharacterValidation);
            }

            
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CharacterModel obj)
        {
            var account = _db.ApplicationUserModel.FirstOrDefault(x => x.UserName == User.Identity.Name);
            obj.AccountNameOwner = User.Identity.Name;

            account.Character = new CharacterModel()
            {
                Id = obj.Id,
                CharacterName = obj.CharacterName,
                Health = obj.Health,
                Dmg = obj.Dmg,
                Job = obj.Job
            };

            _db.Update(account);

            _db.SaveChanges();

            return RedirectToAction("Index");
      
        }


    }
}

FullstackMVC/Controllers/MapController.cs
using FullstackMVC.Data;
using FullstackMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FullstackMVC.Controllers
{
    public class MapController : Controller
    {
        private readonly ApplicationDbContext _db;

        public MapController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<MapModel> map = _db.MapModel;

            return View(map);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(MapModel obj)
        {
            if(ModelState.IsValid)
            {
                _db.MapModel.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }





        //Get for edit
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.MapModel.Find(id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //post edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(MapModel obj)
        {
            if (ModelState.IsValid)
            {
                _db.MapModel.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }




        //Get for delete
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.MapModel.Find(id);

            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //post delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.MapModel.Find(id);

            if (obj == null)
            {
                return NotFound();
            }
            _db.MapModel.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

FullstackMVC/Controllers/MonsterController.cs
using FullstackMVC.Data;
using FullstackMVC.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace FullstackMVC.Controllers
{
    public class MonsterController : Controller
    {
        private readonly ApplicationDbContext _db;

        private readonly IWebHostEnvironment _webHostEnvironment;
        public MonsterController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<MonsterModel> MonsterList = _db.MonsterModel.Include(x=>x.MonsterTypeModel).Include(x=>x.MapModel);

            return View(MonsterList);
        }

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            MonsterVM monsterVM = new MonsterVM()
            {
                Monster = new MonsterModel(),
                MonsterTypeSelectList = _db.MonsterType.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }),
                MapSelectList = _db.MapModel.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                })
            };
            if(id == null)
            {
                return View(monsterVM);
            }
            else
            {
                monsterVM.Monster = _db.MonsterModel.Find(id);
                if (monsterVM.Monster == null)
                {
                    return NotFound();
                }
            }
            return View(monsterVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(MonsterVM monsterVM)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                string webPath = _webHostEnvironment.WebRootPath;

                if(monsterVM.Monster.Id == 0)
                {
                    string upload = webPath + Consts.ImagePath;
                    string fileName = Guid.NewGuid().ToString();
                    string extension = Path.GetExtension(files[0].FileName);
                    using(var fileStream = new FileStream(Path.Combine(upload,fileName+extension),FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    monsterVM.Monster.Image = fileName + extension;
                    _db.MonsterModel.Add(monsterVM.Monster);
                }

                else
                {
                    var dbObject = _db.MonsterModel.AsNoTracking().FirstOrDefault(x => x.Id == monsterVM.Monster.Id);

                    if(files.Count > 0)
                    {
                        string upload = webPath + Consts.ImagePath;
                        string fileName = Guid.NewGuid().ToString();
                        string extension = Path.GetExtension(files[0].FileName);
                        var oldImg = Path.Combine(upload, dbObject.Image);

                        if (System.IO.File.Exists(oldImg))
                        {
                            System.IO.File.Delete(oldImg);
                        }
                        using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);
                        }

                        monsterVM.Monster.Image = fileName + extension;
                    }
                    else
                    {
                        monsterVM.Monster.Image = dbObject.Image;
                    }
                    _db.MonsterModel.Update(monsterVM.Monster);
                }

                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(monsterVM);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.MonsterModel.Find(id);
            MonsterVM monsterVM = new MonsterVM()
            {
                Monster = new MonsterModel()
                {
                    Id = obj.Id,
                    Name = obj.Name,
                    Hp = obj.Hp,
                    Message = obj.Message,
                    DmgMax = obj.DmgMax,
                    DmgMin = obj.DmgMin,
                    Image = obj.Image,
                    MonsterModelId = obj.MonsterModelId
                },
                MonsterTypeSelectList = _db.MonsterType.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }),
                MapSelectList = _db.MapModel.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }),
            };
            if (obj == null)
            {
                return NotFound();
            }
            return View(monsterVM);
        }
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost (int? id)
        {
            var files = HttpContext.Request.Form.Files;
            string webPath = _webHostEnvironment.WebRootPath;
            var dbObject = _db.MonsterModel.AsNoTracking().FirstOrDefault(x => x.Id == id);
            var obj = _db.MonsterModel.Find(id);
            string upload = webPath + Consts.ImagePath;
            string fileName = Guid.NewGuid().ToString();
            var oldImg = Path.Combine(upload, dbObject.Image);

            if (System.IO.File.Exists(oldImg))
            {
                System.IO.File.Delete(oldImg);
            }

            if (obj==null)
            {
                return NotFound();
            }
                _db.MonsterModel.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");     
        }
    }
}

FullstackMVC/Controllers/MonsterTypeController.cs
using FullstackMVC.Data;
using FullstackMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FullstackMVC.Controllers
{
    public class MonsterTypeController : Controller
    {

        private readonly ApplicationDbContext _db;

        public MonsterTypeController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<MonsterTypeModel> monsterTypesList = _db.MonsterType;

            return View(monsterTypesList);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(MonsterTypeModel obj)
        {
            if (ModelState.IsValid)
            {
                _db.MonsterType.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        //Get for edit
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if(id==null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.MonsterType.Find(id);

            if(obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(MonsterTypeModel obj)
        {
            if (ModelState.IsValid)
            {
                _db.MonsterType.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }




        //Get for delete
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.MonsterType.Find(id);

            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //post delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
                var obj = _db.MonsterType.Find(id);

           if(obj==null)
            {
                return NotFound();
            }
                _db.MonsterType.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");     
        }

    }
}

FullstackMVC/Views/Shared/_IndividualMonsterCard.cshtml
@model MonsterModel
    <div class="col-lg-4 col-md-6 pb-4 filter @Model.MapModel.Name.Replace(' ','_')" >
        <!-- Card-->
        <div style="background-image:url('knight.jpg')">
            <div class="card bg-light rounded shadow-sm " style="border:1px solid #222;">
                <div class="card-body px-3 pt-3 pb-1 row">
                    <div class="col-7"><label class="float-left text-dark h5">@Model.Name</label></div>
                    <div class="col-5"><label class="float-right"><span class="text-danger h5">HP: @Model.Hp</span></label> </div>
                </div>

                <img class="card-img-top img-fluid d-block mx-auto mb-3" style="width:200px; height:250px" src="@Consts.ImagePath@Model.Image" alt="Card image cap">
                <div class="card-body p-1 px-3 row">
                    <div class="col-6">
                        <span class="badge p-2 border w-100" style="background-color:lavenderblush">@Model.MonsterTypeModel.Name</span>
                    </div>
                    <div class="col-6 border-0">
                        <span class="badge p-2 border w-100" style="background-color:aliceblue">@Model.MapModel.Name</span>
                    </div>



                    <div class="col-12 p-1">
                        <a asp-action="Attack" asp-route-id="@Model.Id" class="btn btn-info form-control btn-sm p-2" style="height:40px">Attack</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

FullstackMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using FullstackMVC.Utility
@using FullstackMVC.Data
@using FullstackMVC.Engine

@inject IHttpContextAccessor HttpContextAccessor
@inject ApplicationDbContext _db








<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FullstackMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FullstackMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />

                    @{
                        if (User.IsInRole(Consts.UserRole))
                        {
                            var currentUser = _db.ApplicationUserModel.FirstOrDefault(x => x.UserName == User.Identity.Name);
                            currentUser.Character = _db.CharacterModel.FirstOrDefault(x => x.Id == currentUser.CharacterId);

                            if (currentUser.Character != null)
                            {
                                int expNeededToLevelUp = LevelProperties.CalculateExpNeededToLevelUp(currentUser.Character.Experience);
                                @expNeededToLevelUp <i> / </i> @currentUser.Character.Experience; <i class="fas fa-arrow-up " style="padding-left:25px; padding-right:10px"></i>
                                @currentUser.Character.GoldenCoins <i class="fas fa-coins" style="padding-left:25px; padding-right:10px;"></i>
                                <i>Lv.</i> @currentUser.Character.Level;
                            }

                        }
                    }

                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                        </li>
                        <li class="nav-item">
                        </li>
                        <li class="nav-item">
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Game Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Monster" asp-action="Index">Monster</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="Index">Map</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="MonsterType" asp-action="Index">MonsterType</a>
                                <div class="dropdown-divider"></div>
                                @if (User.IsInRole(Consts.AdminRole))
                                {
                                    <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Create Admin</a>
                                }

                                else if (User.IsInRole(Consts.UserRole))
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Character" asp-action="Index">My Character</a>
                                }
                            </div>

                        </li>


                    </ul>

                </div>
            </div>
        </nav>





    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FullstackMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>